// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fsufitch/halebopp-hotspot"
	"github.com/fsufitch/halebopp-hotspot/modules"
)

// Injectors from wire.go:

func initializeDefaultHaleBopp() (*halebopp.HaleBopp, func(), error) {
	battery, cleanup, err := modules.ProvideX278Battery()
	if err != nil {
		return nil, nil, err
	}
	charging, err := modules.ProvideX278Charging()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	haleBopp := &halebopp.HaleBopp{
		Battery:  battery,
		Charging: charging,
	}
	return haleBopp, func() {
		cleanup()
	}, nil
}
